/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1c1b1b",
        "on-primary-container": "#858383",
        "inverse-primary": "#c8c6c5",
        "secondary": "#416656",
        "on-secondary": "#ffffff",
        "secondary-container": "#c3ecd7",
        "on-secondary-container": "#476c5b",
        "secondary-fixed": "#c3ecd7",
        "secondary-fixed-dim": "#a8cfbc",
        "on-secondary-fixed": "#002115",
        "on-secondary-fixed-variant": "#294e3f",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#231a0c",
        "on-tertiary-container": "#90826e",
        "tertiary-fixed": "#f2e0c8",
        "tertiary-fixed-dim": "#d5c4ad",
        "on-tertiary-fixed": "#231a0c",
        "on-tertiary-fixed-variant": "#504534",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#f9f9fa",
        "on-background": "#1a1c1d",
        "surface": "#f9f9fa",
        "surface-dim": "#dadadb",
        "surface-bright": "#f9f9fa",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f4",
        "surface-container": "#eeeeef",
        "surface-container-high": "#e8e8e9",
        "surface-container-highest": "#e2e2e3",
        "surface-variant": "#e2e2e3",
        "on-surface": "#1a1c1d",
        "on-surface-variant": "#444748",
        "inverse-surface": "#2f3132",
        "inverse-on-surface": "#f0f1f2",
        "outline": "#747878",
        "outline-variant": "#c4c7c7",
        "surface-tint": "#5f5e5e",
        "primary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#c8c6c5",
        "on-primary-fixed": "#1c1b1b",
        "on-primary-fixed-variant": "#474746",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "2xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "base": "4px",
        "xs": "8px",
        "sm": "16px",
        "md": "24px",
        "lg": "40px",
        "xl": "64px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "32px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
      },
      boxShadow: {
        "soft-card": "0 4px 24px rgba(0, 0, 0, 0.02)",
        "hover-card": "0 12px 36px rgba(0, 0, 0, 0.05)",
        "float": "0 20px 48px -10px rgba(0, 0, 0, 0.08)",
        "sidebar": "4px 0 24px rgba(0, 0, 0, 0.02)"
      }
    },
  },
  plugins: [],
}
